Support for new resource kinds in Custom K8s Snippets
hyscale/hyscale pull request #333
Opened 2020-10-21 11:30 UTC by Nishanthnishu

2020-11-18 11:04 UTC, vijaySamanuri requested changes

2020-11-18 13:59 UTC, harijvs6 commented on manifest-generator/generator-services/src/main/java/module-info.java
> +    requires client.java;
can we use snakeyaml directly instead of client dependency?

2020-11-18 14:03 UTC, harijvs6 commented on workflow-controller/controller-service/src/main/java/io/hyscale/controller/hooks/VolumeCleanUpHook.java
>  			try {
what happens if a new kind deployed through custom snippets has been deleted in the next deployment? will that resource be deleted from the namespace. any changes required to K8SResourcesCleanUpHook?

2020-11-18 14:18 UTC, harijvs6 commented on manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/processor/PluginProcessor.java
> +            ManifestMeta manifestMeta = new ManifestMeta(kind);
manifestFileGenerator.getYamlManifest() is internally using this to creating resource file name. handle ManifestMeta.identifier?

2020-11-18 14:20 UTC, harijvs6 commented on manifest-generator/generator-services/src/main/java/io/hyscale/generator/services/processor/PluginProcessor.java
> +        List<Manifest> customSnippetsManifestList = getManifestsFromCustomSnippets(serviceMetadata, manifestDir, kindVsCustomSnippets);
better to write all the generated resources in manifestDir at once instead of duplicating code

2020-11-18 14:27 UTC, harijvs6 commented on deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
> +                            boolean isPatched = genericK8sClient.patch(object);
can we try get instead of patch?

2020-11-18 14:42 UTC, harijvs6 commented on deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
> +    private Map<String,CustomObject> getCustomObjects(List<Manifest> manifests) throws HyscaleException {
MultiMap?

2020-11-18 14:48 UTC, harijvs6 commented on deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
> +        List<CustomObject> workloadResources = new ArrayList<>();
use PodParentProvider?

2020-11-18 14:49 UTC, harijvs6 commented on deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
> +        List<CustomObject> workloadResources = new ArrayList<>();
use PodParentProvider?

2020-11-18 14:52 UTC, harijvs6 commented on deployer/deployer-services/src/main/java/io/hyscale/deployer/services/util/K8sResourceDispatcher.java
> +        List<CustomObject> workloadResources = new ArrayList<>();
can be a reusable piece. will be useful somewhere else

2020-11-18 14:58 UTC, harijvs6 requested changes
requested changes

2020-11-24 14:54 UTC, vijaySamanuri approved these changes
LGTM

2020-11-27 13:23 UTC, harijvs6 commented on deployer/deployer-services/src/main/java/io/hyscale/deployer/services/processor/PodParentUtil.java
> +                withNamespace(namespace).forKind(new CustomResourceKind(ResourceKind.SERVICE.getKind(),serviceApiVersion));
better not depend on Service resource. may not work for service without ports

2020-11-30 09:55 UTC, harijvs6 approved these changes
LGTM

2020-11-30 09:55 UTC, merged